// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtEkz4Awm4pvkPMuGnwtqMkR99PRUws4',
    appId: '1:1014410236452:web:3379157eae61c3eb53feb1',
    messagingSenderId: '1014410236452',
    projectId: 'login-flutter-d1fd3',
    authDomain: 'login-flutter-d1fd3.firebaseapp.com',
    storageBucket: 'login-flutter-d1fd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXNc-0OZ-ICxWmHUAU025EqvHeVI7kmY',
    appId: '1:1014410236452:android:a9ce24e17463bfab53feb1',
    messagingSenderId: '1014410236452',
    projectId: 'login-flutter-d1fd3',
    storageBucket: 'login-flutter-d1fd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2cZbdabbL4sv58n_a_53h0bG_naQyQ8',
    appId: '1:1014410236452:ios:4c7b06f86fc2a08b53feb1',
    messagingSenderId: '1014410236452',
    projectId: 'login-flutter-d1fd3',
    storageBucket: 'login-flutter-d1fd3.appspot.com',
    iosClientId: '1014410236452-mflerkoaeu7pbf7k5pkvc80rert8dhco.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2cZbdabbL4sv58n_a_53h0bG_naQyQ8',
    appId: '1:1014410236452:ios:4c7b06f86fc2a08b53feb1',
    messagingSenderId: '1014410236452',
    projectId: 'login-flutter-d1fd3',
    storageBucket: 'login-flutter-d1fd3.appspot.com',
    iosClientId: '1014410236452-mflerkoaeu7pbf7k5pkvc80rert8dhco.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );
}
